### ISSUE TITLE
Alle Channels gehen nicht

### ISSUE THREAD

**Issue by TimK1998** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#510]
Wenn man joined und etwas schreibt, schreibt man im Global-Chat. Wechselt man nun in JEDEN der vorhandenen Channel (auch global) sieht man seine  eigenen gesendeten Nachrichten nicht.

**Comment by TimK1998** [comment]
[16:30:03 ERROR]: Could not pass event AsyncPlayerChatEvent to lostkingdomscore v1.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1407) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1322) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
        at de.lostkingdoms.core.chat.ChatListener.onMessageChannelEventChat(ChatListener.java:33) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor71.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 11 more

**Comment by Timkoe** [comment]
Bei Gildenblock Abbau wird noch keine Message gezeigt

**Comment by Timkoe** [comment]
fix confirmed
